### ISSUE TITLE
Transalation provider interferes with router and context provider

### ISSUE THREAD

**Issue by im-hariprasanth** [bonifacemwanza/react-google-multi-lang#3]
im developing a a react app for witch i use react router and context hook ... when i wrap my app with transalation provider i get an error:useNavigate() may be used only in the context of a <Router> component.
looks like the router is not drilled properly to reach the in components

my main js containing the router parent:
ReactDOM.createRoot(document.getElementById('root')).render(
  <TranslationProvider apiKey={translate} defaultLanguage="en">
  <BrowserRouter>
    <App />
  </BrowserRouter>
  </TranslationProvider>
)

my app :
<UserContextProvider>
    <Routes>
    
      <Route path='/' element={<Landing/>}/>
      <Route path='/register' element={<Register/>}/>
      <Route path='/home' element={<Home/>}/>
      <Route path='/login' element={<Login/>}/>
      <Route path='/viewprofile' element={<User/>}/>
      <Route path='/profile' element={<Profile/>}/>
      <Route path='/admin' element={<Admin/>}/>
      <Route path='/forgotpassword' element={<Forgot/>}/>
      
    </Routes>

    </UserContextProvider>

**Comment by bonifacemwanza** [comment]
can you please paste a more detailed snipped of your code ?

**Comment by im-hariprasanth** [comment]
this is my main jsx:


import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'
import { BrowserRouter } from 'react-router-dom'
import { TranslationProvider } from 'react-google-multi-lang'
const translate = import.meta.env.VITE_TRANSLATE_API_KEY;
ReactDOM.createRoot(document.getElementById('root')).render(
              TranslationProvider apiKey={translate} defaultLanguage="en"
              BrowserRouter
                App /
              /BrowserRouter
            /TranslationProvider
)
//the code is not displaying for aome reason soo ill be removing the <> to make it visible



my app jsx:


import React from 'react'
import { Routes,Route } from 'react-router-dom'
import './App.css'
import Landing from './Pages/Landing'
import Register from './Pages/Register'
import Home from './Pages/Home'
import User from './Pages/User'
import Profile from './Pages/Profile'
import Login from './Pages/Login'
import Admin from './Pages/Admin'
import Forgot from './Pages/Forgot'
import { UserContextProvider } from './Hooks/UserContext'
import LandingBackground from './assets/Images/LandingBackground.jpeg';
import { TranslationProvider, withTranslation } from 'react-google-multi-lang'

const translate = import.meta.env.VITE_TRANSLATE_API_KEY;
function App() {
  
  return (
    UserContextProvider
    Routes
    
      <Route path='/' element={<Landing/>}/>
      <Route path='/register' element={<Register/>}/>
      <Route path='/home' element={<Home/>}/>
      <Route path='/login' element={<Login/>}/>
      <Route path='/viewprofile' element={<User/>}/>
      <Route path='/profile' element={<Profile/>}/>
      <Route path='/admin' element={<Admin/>}/>
      <Route path='/forgotpassword' element={<Forgot/>}/>
      
    </Routes>

    </UserContextProvider>
  )
}

export default withTranslation(App);



my navBar which hold the switch :
i used 
const {setLanguage}=useTranslation();
inside return --> <div onClick={()=>{setLanguage('ta')}} className="langSwitch font-semibold w-16 text-center text-yellow-500 align-middle border-2 border-yellow-500 border-solid rounded-full"> தமிழ் </div>


navBar Component is inside used as :
...
 div className=""
      NavBar new={false}/
      div id="prospect" className="hero relative top-0 z-20  h-screen w-screen bg-hero-background bg-cover bg-center" 
      ...
              

thts the entirety of my translation use

**Comment by bonifacemwanza** [comment]
thanks. looking at it now :)

**Comment by im-hariprasanth** [comment]
thank you man !

**Comment by bonifacemwanza** [comment]
The issue you're encountering with useNavigate() being used outside of the router context is likely due to the incorrect order of how your providers and the router are being wrapped. Specifically, BrowserRouter should wrap the entire application, including the TranslationProvider, because useNavigate() is dependent on the BrowserRouter context.

Fix: Ensure BrowserRouter is the Outer Provider
BrowserRouter must wrap everything, including TranslationProvider and other contexts like UserContextProvider. Here’s how to restructure your code:

```import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';
import { BrowserRouter } from 'react-router-dom';
import { TranslationProvider } from 'react-google-multi-lang';

const translate = import.meta.env.VITE_TRANSLATE_API_KEY;

ReactDOM.createRoot(document.getElementById('root')).render(
  <BrowserRouter>
    <TranslationProvider apiKey={translate} defaultLanguage="en">
      <App />
    </TranslationProvider>
  </BrowserRouter>
);
```


### No changes neededhere 
```
import React from 'react';
import { Routes, Route } from 'react-router-dom';
import './App.css';
import Landing from './Pages/Landing';
import Register from './Pages/Register';
import Home from './Pages/Home';
import User from './Pages/User';
import Profile from './Pages/Profile';
import Login from './Pages/Login';
import Admin from './Pages/Admin';
import Forgot from './Pages/Forgot';
import { UserContextProvider } from './Hooks/UserContext';
import { TranslationProvider, withTranslation } from 'react-google-multi-lang';

function App() {
  return (
    <UserContextProvider>
      <Routes>
        <Route path="/" element={<Landing />} />
        <Route path="/register" element={<Register />} />
        <Route path="/home" element={<Home />} />
        <Route path="/login" element={<Login />} />
        <Route path="/viewprofile" element={<User />} />
        <Route path="/profile" element={<Profile />} />
        <Route path="/admin" element={<Admin />} />
        <Route path="/forgotpassword" element={<Forgot />} />
      </Routes>
    </UserContextProvider>
  );
}

export default withTranslation(App);
```

Wrap the app with BrowserRouter before TranslationProvider: This ensures that routing is fully initialized and the ```useNavigate() ``` hook has the correct context.

No changes are needed in the App.jsx other than ensuring the structure for UserContextProvider and routes remain correct.

**Comment by im-hariprasanth** [comment]
ive already tried that and still it throws same error , even i tried to wrap the whole app with in the app like :

function App() {
  
  return (
    TranslationProvider apiKey={translate} defaultLanguage="en">
    UserContextProvider>
    Routes>
    
      <Route path='/' element={<Landing/>}/>
      <Route path='/register' element={<Register/>}/>
      <Route path='/home' element={<Home/>}/>
      <Route path='/login' element={<Login/>}/>
      <Route path='/viewprofile' element={<User/>}/>
      <Route path='/profile' element={<Profile/>}/>
      <Route path='/admin' element={<Admin/>}/>
      <Route path='/forgotpassword' element={<Forgot/>}/>
      
    </Routes>

    </UserContextProvider>
    </TranslationProvider>
  )
}


and this 
function App() {
  
  return (
    UserContextProvider>
      TranslationProvider apiKey={translate} defaultLanguage="en">
    
    Routes>
    
      <Route path='/' element={<Landing/>}/>
      <Route path='/register' element={<Register/>}/>
      <Route path='/home' element={<Home/>}/>
      <Route path='/login' element={<Login/>}/>
      <Route path='/viewprofile' element={<User/>}/>
      <Route path='/profile' element={<Profile/>}/>
      <Route path='/admin' element={<Admin/>}/>
      <Route path='/forgotpassword' element={<Forgot/>}/>
      
    </Routes>
    </TranslationProvider>
    </UserContextProvider>
   
  )

and even this :
function App() {
  
  return (
    UserContextProvider>
      
    
    Routes>
    TranslationProvider apiKey={translate} defaultLanguage="en">
      <Route path='/' element={<Landing/>}/>
      <Route path='/register' element={<Register/>}/>
      <Route path='/home' element={<Home/>}/>
      <Route path='/login' element={<Login/>}/>
      <Route path='/viewprofile' element={<User/>}/>
      <Route path='/profile' element={<Profile/>}/>
      <Route path='/admin' element={<Admin/>}/>
      <Route path='/forgotpassword' element={<Forgot/>}/>
      </TranslationProvider>
    </Routes>
    
    </UserContextProvider>
   
  )
}

for all of these it throws :
Uncaught Error: useNavigate() may be used only in the context of a <Router> component.

ive used useTranslation with in the navbar thats inside every page  as :  const {setLanguage}=useTranslation();
and setLangage inside the div tag
div onClick={()=>{console.log("im in");setLanguage('ta')}} className="langSwitch font-semibold w-16 text-center text-yellow-500 align-middle border-2 border-yellow-500 border-solid rounded-full"> தமிழ் </div>

**Comment by bonifacemwanza** [comment]
here is my implementation with Navigation and another use context
i tested on my env its working like this, can you try to follow how i did it and let me know how it will woorkfor you ?
 https://github.com/bonifacemwanza/multiple-lang-react

**Comment by im-hariprasanth** [comment]
thanks for  your great work man

**Comment by bonifacemwanza** [comment]
you are welcome
